version: '2'
services:
  rainloop:
    container_name: "rainloop"
#    image: solidnerd/rainloop:1.10.5.192
    build: .
    volumes:
      - ./data:/var/www/rainloop/data
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
